# Generated by Django 5.2.1 on 2025-06-09 13:34

import django_ckeditor_5.fields
from django.db import migrations, models


def create_policy(apps, schema_editor):
    Policy = apps.get_model("policy", "Policy")
    Policy.objects.create(
        name="Политика конфиденциальности", slug="privacy", content="<p>политика конфиденциальности</p>"
    )
    Policy.objects.create(
        name="Пользовательское соглашение", slug="agreement", content="<p>пользовательское соглашение</p>"
    )


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Policy",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=32, unique=True, verbose_name="название")),
                ("slug", models.SlugField(max_length=32, unique=True)),
                ("content", django_ckeditor_5.fields.CKEditor5Field(verbose_name="контент")),
            ],
            options={
                "verbose_name": "условие",
                "verbose_name_plural": "условия",
            },
        ),
        migrations.RunPython(create_policy, None),
    ]
