# Generated by Django 5.2.1 on 2025-06-08 10:23

import apps.metadata.mixins
import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


def create_sitemap(apps, schema_editor):
    Sitemap = apps.get_model("metadata", "Sitemap")
    Sitemap.objects.create()


def create_robots(apps, schema_editor):
    Robots = apps.get_model("metadata", "Robots")
    Robots.objects.create(
        text="robots\nUser-agent: *\n\nDisallow: *?\nDisallow: */cart\nDisallow: */privacy\nDisallow: */agreement\n\nAllow: */?_rsc=\nAllow: *?*.png\n\nSitemap: https://stroy-technology.ru/sitemap.xml"
    )


def create_metagenerationrule(apps, schema_editor):
    MetaGenerationRule = apps.get_model("metadata", "MetaGenerationRule")

    MetaGenerationRule.objects.create(type="grp", title="{name}", description="{name}")
    MetaGenerationRule.objects.create(type="ctg", title="{name}", description="{name}")
    MetaGenerationRule.objects.create(type="prd", title="{name}", description="{name}")


def create_meta(apps, schema_editor):
    arr = [
        (
            apps.get_model("metadata", "CategoryGroupPageMetadata"),
            apps.get_model("catalog", "ProductCategoryGroup"),
        ),
        (
            apps.get_model("metadata", "CategoryPageMetadata"),
            apps.get_model("catalog", "ProductCategory"),
        ),
        (
            apps.get_model("metadata", "ProductPageMetadata"),
            apps.get_model("catalog", "Product"),
        ),
        (
            apps.get_model("metadata", "PostPageMetadata"),
            apps.get_model("blog", "Post"),
        ),
    ]

    for item in arr:
        MetadataModel = item[0]
        create_list = []
        entity_qs = item[1].objects.all()
        for object in entity_qs:
            create_list.append(MetadataModel(title=object.name, description=object.name, entity=object))
        MetadataModel.objects.bulk_create(create_list, 1000)

    create_list = []
    StaticPageMetadata = apps.get_model("metadata", "StaticPageMetadata")
    Page = apps.get_model("pages", "Page")
    for object in Page.objects.all():
        create_list.append(
            StaticPageMetadata(
                title="Строительные технологии",
                description="Производство и поставка строительного оборудования от производителя Строительные технологии: хомуты для лесов, опалубка. Выгодные цены. Быстрая поставка по Росиии.",
                entity=object,
            )
        )
    StaticPageMetadata.objects.bulk_create(create_list, 1000)


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("blog", "0001_initial"),
        ("catalog", "0001_initial"),
        ("pages", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MetaGenerationRule",
            fields=[
                (
                    "type",
                    models.CharField(
                        choices=[("grp", "Группа категорий"), ("ctg", "Категория"), ("prd", "Товар")],
                        max_length=3,
                        primary_key=True,
                        serialize=False,
                        verbose_name="тип",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="правило генерации Title")),
                ("description", models.TextField(verbose_name="правило генерации Description")),
            ],
            options={
                "verbose_name": "правило генерации метатегов",
                "verbose_name_plural": "правила генерации метатегов",
            },
        ),
        migrations.CreateModel(
            name="Robots",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("text", models.TextField(verbose_name="robots.txt")),
            ],
            options={
                "verbose_name": "robots.txt",
                "verbose_name_plural": "robots.txt",
            },
        ),
        migrations.CreateModel(
            name="Sitemap",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
            ],
        ),
        migrations.CreateModel(
            name="ProductPageMetadata",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(blank=True, max_length=255, verbose_name="title")),
                ("description", models.TextField(blank=True, verbose_name="description")),
                (
                    "noindex_follow",
                    models.BooleanField(default=False, verbose_name='<meta name="robots" content="noindex, follow">'),
                ),
                (
                    "change_freq",
                    models.CharField(
                        choices=[
                            ("always", "always"),
                            ("hourly", "hourly"),
                            ("daily", "daily"),
                            ("weekly", "weekly"),
                            ("monthly", "monthly"),
                            ("yearly", "yearly"),
                            ("never", "never"),
                        ],
                        default="yearly",
                        max_length=7,
                        verbose_name="changefreq",
                    ),
                ),
                (
                    "priority",
                    models.DecimalField(
                        decimal_places=1,
                        default=1.0,
                        max_digits=2,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.1")),
                            django.core.validators.MaxValueValidator(Decimal("1.0")),
                        ],
                        verbose_name="priority",
                    ),
                ),
                (
                    "entity",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, related_name="metadata", to="catalog.product"
                    ),
                ),
                (
                    "rule",
                    models.ForeignKey(
                        default="prd", on_delete=django.db.models.deletion.RESTRICT, to="metadata.metagenerationrule"
                    ),
                ),
                (
                    "sitemap",
                    models.ForeignKey(
                        default=1,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="products",
                        to="metadata.sitemap",
                    ),
                ),
            ],
            options={
                "verbose_name": "метаданные для страницы",
                "verbose_name_plural": "метаданные для страниц",
                "abstract": False,
            },
            bases=(apps.metadata.mixins.MetaGenerationRuleMixin, models.Model),
        ),
        migrations.CreateModel(
            name="PostPageMetadata",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(blank=True, max_length=255, verbose_name="title")),
                ("description", models.TextField(blank=True, verbose_name="description")),
                (
                    "noindex_follow",
                    models.BooleanField(default=False, verbose_name='<meta name="robots" content="noindex, follow">'),
                ),
                (
                    "change_freq",
                    models.CharField(
                        choices=[
                            ("always", "always"),
                            ("hourly", "hourly"),
                            ("daily", "daily"),
                            ("weekly", "weekly"),
                            ("monthly", "monthly"),
                            ("yearly", "yearly"),
                            ("never", "never"),
                        ],
                        default="yearly",
                        max_length=7,
                        verbose_name="changefreq",
                    ),
                ),
                (
                    "priority",
                    models.DecimalField(
                        decimal_places=1,
                        default=1.0,
                        max_digits=2,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.1")),
                            django.core.validators.MaxValueValidator(Decimal("1.0")),
                        ],
                        verbose_name="priority",
                    ),
                ),
                (
                    "entity",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, related_name="metadata", to="blog.post"
                    ),
                ),
                (
                    "sitemap",
                    models.ForeignKey(
                        default=1,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="posts",
                        to="metadata.sitemap",
                    ),
                ),
            ],
            options={
                "verbose_name": "метаданные для страницы",
                "verbose_name_plural": "метаданные для страниц",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="CategoryPageMetadata",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(blank=True, max_length=255, verbose_name="title")),
                ("description", models.TextField(blank=True, verbose_name="description")),
                (
                    "noindex_follow",
                    models.BooleanField(default=False, verbose_name='<meta name="robots" content="noindex, follow">'),
                ),
                (
                    "change_freq",
                    models.CharField(
                        choices=[
                            ("always", "always"),
                            ("hourly", "hourly"),
                            ("daily", "daily"),
                            ("weekly", "weekly"),
                            ("monthly", "monthly"),
                            ("yearly", "yearly"),
                            ("never", "never"),
                        ],
                        default="yearly",
                        max_length=7,
                        verbose_name="changefreq",
                    ),
                ),
                (
                    "priority",
                    models.DecimalField(
                        decimal_places=1,
                        default=1.0,
                        max_digits=2,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.1")),
                            django.core.validators.MaxValueValidator(Decimal("1.0")),
                        ],
                        verbose_name="priority",
                    ),
                ),
                (
                    "entity",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="metadata",
                        to="catalog.productcategory",
                    ),
                ),
                (
                    "rule",
                    models.ForeignKey(
                        default="ctg", on_delete=django.db.models.deletion.RESTRICT, to="metadata.metagenerationrule"
                    ),
                ),
                (
                    "sitemap",
                    models.ForeignKey(
                        default=1,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="categories",
                        to="metadata.sitemap",
                    ),
                ),
            ],
            options={
                "verbose_name": "метаданные для страницы",
                "verbose_name_plural": "метаданные для страниц",
                "abstract": False,
            },
            bases=(apps.metadata.mixins.MetaGenerationRuleMixin, models.Model),
        ),
        migrations.CreateModel(
            name="CategoryGroupPageMetadata",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(blank=True, max_length=255, verbose_name="title")),
                ("description", models.TextField(blank=True, verbose_name="description")),
                (
                    "noindex_follow",
                    models.BooleanField(default=False, verbose_name='<meta name="robots" content="noindex, follow">'),
                ),
                (
                    "change_freq",
                    models.CharField(
                        choices=[
                            ("always", "always"),
                            ("hourly", "hourly"),
                            ("daily", "daily"),
                            ("weekly", "weekly"),
                            ("monthly", "monthly"),
                            ("yearly", "yearly"),
                            ("never", "never"),
                        ],
                        default="yearly",
                        max_length=7,
                        verbose_name="changefreq",
                    ),
                ),
                (
                    "priority",
                    models.DecimalField(
                        decimal_places=1,
                        default=1.0,
                        max_digits=2,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.1")),
                            django.core.validators.MaxValueValidator(Decimal("1.0")),
                        ],
                        verbose_name="priority",
                    ),
                ),
                (
                    "entity",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="metadata",
                        to="catalog.productcategorygroup",
                    ),
                ),
                (
                    "rule",
                    models.ForeignKey(
                        default="grp", on_delete=django.db.models.deletion.RESTRICT, to="metadata.metagenerationrule"
                    ),
                ),
                (
                    "sitemap",
                    models.ForeignKey(
                        default=1,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="groups",
                        to="metadata.sitemap",
                    ),
                ),
            ],
            options={
                "verbose_name": "метаданные для страницы",
                "verbose_name_plural": "метаданные для страниц",
                "abstract": False,
            },
            bases=(apps.metadata.mixins.MetaGenerationRuleMixin, models.Model),
        ),
        migrations.CreateModel(
            name="StaticPageMetadata",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(blank=True, max_length=255, verbose_name="title")),
                ("description", models.TextField(blank=True, verbose_name="description")),
                (
                    "noindex_follow",
                    models.BooleanField(default=False, verbose_name='<meta name="robots" content="noindex, follow">'),
                ),
                (
                    "change_freq",
                    models.CharField(
                        choices=[
                            ("always", "always"),
                            ("hourly", "hourly"),
                            ("daily", "daily"),
                            ("weekly", "weekly"),
                            ("monthly", "monthly"),
                            ("yearly", "yearly"),
                            ("never", "never"),
                        ],
                        default="yearly",
                        max_length=7,
                        verbose_name="changefreq",
                    ),
                ),
                (
                    "priority",
                    models.DecimalField(
                        decimal_places=1,
                        default=1.0,
                        max_digits=2,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.1")),
                            django.core.validators.MaxValueValidator(Decimal("1.0")),
                        ],
                        verbose_name="priority",
                    ),
                ),
                (
                    "entity",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, related_name="metadata", to="pages.page"
                    ),
                ),
                (
                    "sitemap",
                    models.ForeignKey(
                        default=1,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="static",
                        to="metadata.sitemap",
                    ),
                ),
            ],
            options={
                "verbose_name": "метаданные для страницы",
                "verbose_name_plural": "метаданные для страниц",
                "abstract": False,
            },
        ),
        migrations.RunPython(create_sitemap, None),
        migrations.RunPython(create_robots, None),
        migrations.RunPython(create_metagenerationrule, None),
        migrations.RunPython(create_meta, None),
    ]
