"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 5.2.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load environment variables from .env file
load_dotenv(override=True)


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv("DEBUG")

ALLOWED_HOSTS = [os.getenv("ALLOWED_HOSTS")]


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    # apps
    "shared",
    "apps.blog",
    "apps.company",
    "apps.catalog",
    "apps.requests",
    "apps.pages",
    "apps.metadata",
    # third
    "rest_framework",
    "django_filters",
    "corsheaders",
    "django_ckeditor_5",
    "nested_admin",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "core.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "core.wsgi.application"


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "ru"

TIME_ZONE = "Asia/Yekaterinburg"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"
# STATICFILES_DIRS = [
#     os.path.join(BASE_DIR, "shared", "staticfiles"),
# ]
STATIC_ROOT = os.path.join(BASE_DIR, "static")

MEDIA_URL = "media/"
MEDIA_ROOT = os.path.join(BASE_DIR, "media")

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


EMAIL_HOST = os.getenv("EMAIL_HOST")
EMAIL_PORT = int(os.getenv("EMAIL_PORT"))
EMAIL_HOST_USER = os.getenv("EMAIL_HOST_USER")
EMAIL_HOST_PASSWORD = os.getenv("EMAIL_HOST_PASSWORD")
# EMAIL_USE_TLS = True
EMAIL_USE_SSL = True


DATABASES = {
    "default": {
        "ENGINE": os.getenv("DB_ENGINE"),
        "NAME": os.getenv("DB_NAME") or BASE_DIR / "db.sqlite3",
        "USER": os.getenv("DB_USER"),
        "PASSWORD": os.getenv("DB_PASSWORD"),
        "HOST": "localhost",
        "PORT": "",
    }
}


# csrf
CSRF_TRUSTED_ORIGINS = os.getenv("CSRF_TRUSTED_ORIGINS").split(",") if os.getenv("CSRF_TRUSTED_ORIGINS") else []


# CORS
CORS_ALLOWED_ORIGINS = os.getenv("CORS_ALLOWED_ORIGINS").split(",") if os.getenv("CORS_ALLOWED_ORIGINS") else []


# drf
REST_FRAMEWORK = {
    "ORDERING_PARAM": "sort",
    "DEFAULT_RENDERER_CLASSES": ("rest_framework.renderers.JSONRenderer",),
}


# ckeditor
customColorPalette = [
    {"color": "hsl(4, 90%, 58%)", "label": "Red"},
    {"color": "hsl(340, 82%, 52%)", "label": "Pink"},
    {"color": "hsl(291, 64%, 42%)", "label": "Purple"},
    {"color": "hsl(262, 52%, 47%)", "label": "Deep Purple"},
    {"color": "hsl(231, 48%, 48%)", "label": "Indigo"},
    {"color": "hsl(207, 90%, 54%)", "label": "Blue"},
]

CKEDITOR_5_CUSTOM_CSS = "css/ckeditor5/style.css"  # optional
CKEDITOR_5_FILE_STORAGE = "shared.utils.CustomStorage"  # optional
CK_EDITOR_5_UPLOAD_FILE_VIEW_NAME = "custom_upload_file"
CKEDITOR_5_CONFIGS = {
    "default": {
        "toolbar": None,
        "language": "ru",
    },
    "product": {
        "toolbar": [
            "heading",
            "|",
            "bold",
            "underline",
            "|",
            "sourceEditing",
            "bulletedList",
            "numberedList",
        ],
        "heading": {
            "options": [
                {"model": "paragraph", "title": "Параграф", "class": "ck-heading_paragraph"},
            ]
        },
        "list": {
            "properties": {
                "styles": "false",
            }
        },
    },
    "post": {
        "toolbar": [
            "heading",
            "|",
            "bold",
            "underline",
            "strikethrough",
            "|",
            "sourceEditing",
            "uploadImage",
            "bulletedList",
            "numberedList",
            "|",
        ],
        "image": {
            "toolbar": [
                "imageTextAlternative",
                "|",
                "imageStyle:block",
                # "imageStyle:inline",
                "|",
            ],
            "styles": [
                "full",
                "side",
                "alignCenter",
            ],
        },
        # "table": {
        #     "contentToolbar": ["tableColumn", "tableRow", "mergeTableCells", "tableProperties", "tableCellProperties"],
        #     "tableProperties": {"borderColors": customColorPalette, "backgroundColors": customColorPalette},
        #     "tableCellProperties": {"borderColors": customColorPalette, "backgroundColors": customColorPalette},
        # },
        "heading": {
            "options": [
                {"model": "paragraph", "title": "Параграф", "class": "ck-heading_paragraph"},
                {"model": "heading2", "view": "h2", "title": "Заголовок 2", "class": "ck-heading_heading2"},
                {"model": "heading3", "view": "h3", "title": "Заголовок 3", "class": "ck-heading_heading3"},
            ]
        },
        "mediaEmbed": {
            "previewsInData": True,
        },
        "list": {
            "properties": {
                "styles": "false",
            }
        },
    },
    "faq": {
        "toolbar": [
            "heading",
            "|",
            "bold",
            "underline",
            "strikethrough",
            "|",
            "sourceEditing",
            "bulletedList",
            "numberedList",
        ],
        "heading": {
            "options": [
                {"model": "paragraph", "title": "Параграф", "class": "ck-heading_paragraph"},
                {"model": "heading2", "view": "h2", "title": "Заголовок 2", "class": "ck-heading_heading2"},
            ]
        },
        "list": {
            "properties": {
                "styles": "false",
            }
        },
    },
    "policy": {
        "toolbar": [
            "heading",
            "|",
            "bold",
            "underline",
            "|",
            "sourceEditing",
            "bulletedList",
        ],
        "heading": {
            "options": [
                {"model": "paragraph", "title": "Параграф", "class": "ck-heading_paragraph"},
                {"model": "heading2", "view": "h2", "title": "Заголовок 2", "class": "ck-heading_heading2"},
                {"model": "heading3", "view": "h3", "title": "Заголовок 3", "class": "ck-heading_heading3"},
            ]
        },
        "list": {
            "properties": {
                "styles": "false",
            }
        },
    },
}


SITE_DOMAIN = os.getenv("SITE_DOMAIN")


REDIS_HOST = "localhost"
REDIS_PORT = "6379"
CELERY_BROKER_URL = "redis://" + REDIS_HOST + ":" + REDIS_PORT + "/0"
CELERY_BROKER_TRANSPORT_OPTIONS = {"visibility_timeout": 3600}
CELERY_RESULT_BACKEND = "redis://" + REDIS_HOST + ":" + REDIS_PORT + "/0"
CELERY_ACCEPT_CONTENT = ["application/json"]
CELERY_TASK_SERIALIZER = "json"
CELERY_RESULT_SERIALIZER = "json"


PROJECT_LOGGING_DIR = os.path.join(BASE_DIR.parent, "logs")
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {"simple": {"format": "{process}-{thread} {levelname} {asctime} {message}", "style": "{"}},
    "handlers": {
        "email.file": {
            "level": "INFO",
            "class": "logging.FileHandler",
            "filename": os.path.join(PROJECT_LOGGING_DIR, "email.log"),
            "formatter": "simple",
        },
    },
    "loggers": {"stroy.email": {"handlers": ["email.file"], "level": "INFO", "propogate": False}},
}
