# Generated by Django 5.2.1 on 2025-05-23 11:46

import django_ckeditor_5.fields
import shared.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FaqCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=24, unique=True, verbose_name='название')),
            ],
            options={
                'verbose_name': 'FAQ категория',
                'verbose_name_plural': 'FAQ категории',
            },
        ),
        migrations.CreateModel(
            name='PostCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=24, unique=True, verbose_name='название')),
            ],
            options={
                'verbose_name': 'блог категория',
                'verbose_name_plural': 'блог категории',
            },
        ),
        migrations.CreateModel(
            name='Faq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255, unique=True, verbose_name='вопрос')),
                ('answer', django_ckeditor_5.fields.CKEditor5Field(verbose_name='ответ')),
                ('categories', models.ManyToManyField(blank=True, related_name='faqs', to='blog.faqcategory', verbose_name='категории')),
            ],
            options={
                'verbose_name': 'FAQ (Часто задаваемый вопрос)',
                'verbose_name_plural': 'FAQ (Часто задаваемые вопросы)',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=112, unique=True, verbose_name='заголовок')),
                ('slug', models.SlugField(max_length=128, unique=True, verbose_name='url (slug)')),
                ('excerpt', models.TextField(max_length=128, verbose_name='краткое описание')),
                ('preview', models.ImageField(upload_to=shared.utils.post_preview_upload_to, verbose_name='изображение карточки поста')),
                ('content', django_ckeditor_5.fields.CKEditor5Field(verbose_name='пост')),
                ('created', models.DateField(auto_now_add=True, verbose_name='дата создания')),
                ('updated', models.DateField(auto_now=True, verbose_name='дата обновления')),
                ('categories', models.ManyToManyField(blank=True, related_name='posts', to='blog.postcategory', verbose_name='категории поста')),
            ],
            options={
                'verbose_name': 'блог пост',
                'verbose_name_plural': 'блог посты',
                'ordering': ('created', '-id'),
            },
        ),
    ]
