# Generated by Django 5.2.1 on 2025-06-09 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('-created', '-id'), 'verbose_name': 'блог пост', 'verbose_name_plural': 'блог посты'},
        ),
    ]
