# Generated by Django 5.2.1 on 2025-06-21 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_post_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='video',
            field=models.URLField(blank=True, null=True, verbose_name='ссылка на видео'),
        ),
    ]
