# Generated by Django 5.2.1 on 2025-06-04 05:52

import django.core.validators
import django.db.models.deletion
import shared.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommercialRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, validators=[django.core.validators.MinLengthValidator(2), django.core.validators.MaxLengthValidator(32)], verbose_name='имя')),
                ('phone', models.CharField(max_length=20, verbose_name='номер телефона')),
                ('comment', models.TextField(blank=True, verbose_name='комментарий')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='дата')),
                ('file', models.FileField(upload_to=shared.utils.commercial_request_file_upload_to, verbose_name='чертеж')),
            ],
            options={
                'verbose_name': 'запрос коммерческого предложения',
                'verbose_name_plural': 'запросы коммерческих предложений',
            },
        ),
        migrations.CreateModel(
            name='ConsultationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, validators=[django.core.validators.MinLengthValidator(2), django.core.validators.MaxLengthValidator(32)], verbose_name='имя')),
                ('phone', models.CharField(max_length=20, verbose_name='номер телефона')),
                ('comment', models.TextField(blank=True, verbose_name='комментарий')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='дата')),
            ],
            options={
                'verbose_name': 'запрос консультации',
                'verbose_name_plural': 'запросы консультаций',
            },
        ),
        migrations.CreateModel(
            name='OrderRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, validators=[django.core.validators.MinLengthValidator(2), django.core.validators.MaxLengthValidator(32)], verbose_name='имя')),
                ('phone', models.CharField(max_length=20, verbose_name='номер телефона')),
                ('comment', models.TextField(blank=True, verbose_name='комментарий')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='дата')),
            ],
            options={
                'verbose_name': 'запрос товаров',
                'verbose_name_plural': 'запросы товаров',
            },
        ),
        migrations.CreateModel(
            name='OrderRequestItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='количество')),
                ('price', models.PositiveIntegerField(verbose_name='цена на момент запроса со скидкой')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='requests.orderrequest', verbose_name='заказ')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.product', verbose_name='товар')),
            ],
            options={
                'verbose_name': 'товар',
                'verbose_name_plural': 'товары',
            },
        ),
    ]
