# Generated by Django 5.2.1 on 2025-06-20 12:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_productprice_and_more'),
        ('requests', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderrequestitem',
            name='variant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.productprice', verbose_name='текущее название вариации товара'),
        ),
        migrations.AddField(
            model_name='orderrequestitem',
            name='variant_text',
            field=models.CharField(default='', max_length=24, verbose_name='название вариации на момент запроса'),
            preserve_default=False,
        ),
    ]
