# Generated by Django 5.2.1 on 2025-06-22 16:26

import apps.requests.validators
import shared.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0002_orderrequestitem_variant_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commercialrequest',
            name='file',
            field=models.FileField(upload_to=shared.utils.commercial_request_file_upload_to, validators=[apps.requests.validators.FileValidator(content_types='application/pdf', max_size=10485760)], verbose_name='чертеж'),
        ),
    ]
