# Generated by Django 5.2.1 on 2025-07-02 19:40

import apps.requests.validators
import shared.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0003_alter_commercialrequest_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commercialrequest',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=shared.utils.commercial_request_file_upload_to, validators=[apps.requests.validators.FileValidator(content_types='application/pdf', max_size=10485760)], verbose_name='чертеж'),
        ),
    ]
