# Generated by Django 5.2.1 on 2025-08-12 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0004_alter_commercialrequest_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='commercialrequest',
            name='addition',
            field=models.TextField(blank=True, verbose_name='доп. информация'),
        ),
        migrations.AddField(
            model_name='consultationrequest',
            name='addition',
            field=models.TextField(blank=True, verbose_name='доп. информация'),
        ),
        migrations.AddField(
            model_name='orderrequest',
            name='addition',
            field=models.TextField(blank=True, verbose_name='доп. информация'),
        ),
    ]
