# Generated by Django 5.2.1 on 2025-05-24 08:55

import apps.company.fields
import django.db.models.deletion
from django.db import migrations, models


def create_contacts(apps, schema_editor):
    Contact = apps.get_model("company", "Contact")
    Contact.objects.create(email="", phone="")


def create_requisites(apps, schema_editor):
    Requisite = apps.get_model("company", "Requisite")
    Requisite.objects.create(name="")


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("email", models.EmailField(max_length=254, verbose_name="основной email")),
                ("phone", apps.company.fields.PhoneField(verbose_name="основной номер телефона")),
            ],
            options={
                "verbose_name": "контакты",
                "verbose_name_plural": "контакты",
            },
        ),
        migrations.CreateModel(
            name="Requisite",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=128, verbose_name="название организации")),
            ],
            options={
                "verbose_name": "реквизиты",
                "verbose_name_plural": "реквизиты",
            },
        ),
        migrations.CreateModel(
            name="Address",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("city", models.CharField(max_length=32, unique=True, verbose_name="город")),
                ("address", models.CharField(max_length=64, verbose_name="адрес")),
                ("caption", models.CharField(max_length=64, verbose_name="подпись")),
                ("weekdays", models.CharField(max_length=48, verbose_name="режим работы по будням")),
                ("weekends", models.CharField(max_length=48, verbose_name="режим работы по выходным")),
                ("phone", apps.company.fields.PhoneField(verbose_name="номер телефона")),
                (
                    "contact",
                    models.ForeignKey(
                        default=1,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="addresses",
                        to="company.contact",
                    ),
                ),
            ],
            options={
                "verbose_name": "адрес",
                "verbose_name_plural": "адреса",
            },
        ),
        migrations.CreateModel(
            name="AdditionalPhone",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("caption", models.CharField(max_length=64, verbose_name="подпись телефона")),
                ("value", apps.company.fields.PhoneField(verbose_name="номер телефона")),
                (
                    "contact",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, related_name="phones", to="company.contact"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AdditionalEmail",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("caption", models.CharField(max_length=64, verbose_name="подпись email")),
                ("value", models.EmailField(max_length=254, verbose_name="email")),
                (
                    "contact",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, related_name="emails", to="company.contact"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RequisiteItem",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=32, unique=True, verbose_name="название")),
                ("value", models.CharField(max_length=128, verbose_name="значение")),
                (
                    "organization",
                    models.ForeignKey(
                        default=1,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="requisites",
                        to="company.requisite",
                    ),
                ),
            ],
            options={
                "verbose_name": "элемент реквизитов",
                "verbose_name_plural": "элементы реквизитов",
            },
        ),
        migrations.RunPython(create_contacts, None),
        migrations.RunPython(create_requisites, None),
    ]
