# Generated by Django 5.2.1 on 2025-06-06 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='coordinates',
            field=models.CharField(max_length=32, null=True, verbose_name='координаты'),
        ),
    ]
