# Generated by Django 5.2.1 on 2025-06-10 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_address_coordinates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='address',
            field=models.CharField(max_length=128, verbose_name='адрес'),
        ),
    ]
