# Generated by Django 5.2.1 on 2025-06-10 21:28

import apps.company.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_alter_address_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='coordinates',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='координаты'),
        ),
        migrations.AlterField(
            model_name='address',
            name='phone',
            field=apps.company.fields.PhoneField(blank=True, null=True, verbose_name='номер телефона'),
        ),
    ]
