# Generated by Django 5.2.1 on 2025-06-10 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_alter_address_coordinates_alter_address_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.CharField(max_length=32, verbose_name='город'),
        ),
    ]
