# Generated by Django 5.2.1 on 2025-06-25 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0005_alter_address_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='tg',
            field=models.CharField(default='', max_length=24, verbose_name='telegram'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contact',
            name='wa',
            field=models.CharField(default='', max_length=24, verbose_name='whatsapp'),
            preserve_default=False,
        ),
    ]
