# Generated by Django 5.2.1 on 2025-07-03 18:19

import apps.company.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0006_contact_tg_contact_wa'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='phone2',
            field=apps.company.fields.PhoneField(blank=True, null=True, verbose_name='основной номер телефона 2'),
        ),
    ]
