# Generated by Django 5.2.1 on 2025-06-08 09:29

from django.db import migrations, models


def create_pages(apps, schema_editor):
    Page = apps.get_model("pages", "Page")

    Page.objects.create(
        name="Главная", slug="home", title="Производство и поставка<br>комплектующих для<br>строительных объектов"
    )
    Page.objects.create(name="О компании", slug="about", title="О компании<br>Строительные технологии")
    Page.objects.create(name="Каталог", slug="catalog", title="Каталог")
    Page.objects.create(name="Партнерам", slug="partners", title="Партнерам")
    Page.objects.create(name="Блог", slug="blog", title="Блог")
    Page.objects.create(name="FAQ", slug="faq", title="FAQ (Вопрос - ответ)")
    Page.objects.create(name="Контакты", slug="contacts", title="Контакты")


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Page",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255, unique=True, verbose_name="страница")),
                ("slug", models.SlugField(max_length=64, unique=True)),
                ("title", models.CharField(max_length=64, verbose_name="заголовок страницы")),
            ],
            options={
                "verbose_name": "страница",
                "verbose_name_plural": "страницы",
            },
        ),
        migrations.RunPython(create_pages, None),
    ]
