# Generated by Django 5.2.1 on 2025-06-09 13:34

import django_ckeditor_5.fields
from django.db import migrations, models


def create_content(apps, schema_editor):
    Content = apps.get_model("pages", "Content")
    Content.objects.create(name="Партнерам", slug="partners", content="<p>Партнерам</p>")


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Content",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=32, unique=True, verbose_name="страница")),
                ("slug", models.SlugField(max_length=32, unique=True)),
                ("content", django_ckeditor_5.fields.CKEditor5Field(verbose_name="контент")),
            ],
            options={
                "verbose_name": "содержание страницы",
                "verbose_name_plural": "содержание страниц",
            },
        ),
        migrations.RunPython(create_content, None),
    ]
