# Generated by Django 5.2.1 on 2025-06-11 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='title',
            field=models.CharField(max_length=88, verbose_name='заголовок страницы'),
        ),
    ]
