# Generated by Django 5.2.1 on 2025-06-04 05:52

import django.core.validators
import django.db.models.deletion
import django_ckeditor_5.fields
import shared.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(default=32000, verbose_name='очередность')),
                ('name', models.CharField(max_length=24, verbose_name='название')),
            ],
            options={
                'verbose_name': 'характеристика категории товаров',
                'verbose_name_plural': 'характеристики категорий товаров',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(default=32000, verbose_name='очередность')),
                ('name', models.CharField(max_length=80, unique=True, verbose_name='название')),
                ('slug', models.SlugField(max_length=96, unique=True, verbose_name='url (slug)')),
                ('price', models.PositiveIntegerField(verbose_name='цена')),
                ('discount', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(99), django.core.validators.MinValueValidator(1)], verbose_name='скидка (%)')),
                ('remainder', models.PositiveIntegerField(verbose_name='актуальный остаток')),
                ('stock', models.BooleanField(default=True, verbose_name='в наличии')),
                ('description', django_ckeditor_5.fields.CKEditor5Field(verbose_name='описание товара')),
            ],
            options={
                'verbose_name': 'товар',
                'verbose_name_plural': 'товары',
                'ordering': ('order', 'id'),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(default=32000, verbose_name='очередность')),
                ('name', models.CharField(max_length=48, unique=True, verbose_name='название')),
                ('slug', models.SlugField(max_length=64, unique=True, verbose_name='url (slug)')),
            ],
            options={
                'verbose_name': 'категория товара',
                'verbose_name_plural': 'категории товаров',
                'ordering': ('order', 'id'),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProductCategoryGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(default=32000, verbose_name='очередность')),
                ('name', models.CharField(max_length=48, unique=True, verbose_name='название')),
                ('slug', models.SlugField(max_length=64, unique=True, verbose_name='url (slug)')),
                ('image', models.ImageField(null=True, upload_to=shared.utils.category_group_image_upload_to, verbose_name='картинка')),
            ],
            options={
                'verbose_name': 'группа категории товара',
                'verbose_name_plural': 'группы категории товаров',
                'ordering': ('order', 'id'),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AttributeValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=24, verbose_name='название')),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='catalog.attribute', verbose_name='значение характеристики товара')),
            ],
            options={
                'verbose_name': 'значение характеристики товаров',
                'verbose_name_plural': 'значения характеристик товаров',
            },
        ),
        migrations.CreateModel(
            name='ProductAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(default=32000, verbose_name='очередность')),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attribute_products', to='catalog.attribute', verbose_name='характеристика')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='catalog.product', verbose_name='товар')),
                ('value', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.attributevalue', verbose_name='значение')),
            ],
            options={
                'verbose_name': 'характеристика товара',
                'verbose_name_plural': 'характеристики товаров',
                'ordering': ('order', 'id'),
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='catalog.productcategory', verbose_name='категория товара'),
        ),
        migrations.AddField(
            model_name='attribute',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='catalog.productcategory'),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='group',
            field=models.ManyToManyField(related_name='categories', to='catalog.productcategorygroup', verbose_name='группа категории'),
        ),
        migrations.CreateModel(
            name='ProductDoc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='название документа')),
                ('url', models.FileField(upload_to=shared.utils.product_file_upload_to, verbose_name='документ')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='docs', to='catalog.product', verbose_name='товар')),
            ],
            options={
                'verbose_name': 'документ товара',
                'verbose_name_plural': 'документы товаров',
            },
        ),
        migrations.CreateModel(
            name='ProductImg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.ImageField(upload_to=shared.utils.product_image_upload_to, verbose_name='изображение товара')),
                ('order', models.PositiveSmallIntegerField(default=10, verbose_name='очередность')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='catalog.product', verbose_name='товар')),
            ],
            options={
                'verbose_name': 'изображение товара',
                'verbose_name_plural': 'изображения товара',
                'ordering': ('product', 'order', 'id'),
            },
        ),
        migrations.AddConstraint(
            model_name='attributevalue',
            constraint=models.UniqueConstraint(fields=('name', 'attribute'), name='unique_attribute_value_name_attribute'),
        ),
        migrations.AddConstraint(
            model_name='productattribute',
            constraint=models.UniqueConstraint(fields=('product', 'attribute'), name='unique_product_attribute'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(condition=models.Q(('discount__gte', 1), ('discount__lte', 99)), name='catalog_product_discount_range', violation_error_message='Скидка должна быть в диапазоне от 1 до 99'),
        ),
        migrations.AddConstraint(
            model_name='attribute',
            constraint=models.UniqueConstraint(fields=('name', 'category'), name='unique_attribute_name_category'),
        ),
    ]
