# Generated by Django 5.2.1 on 2025-06-09 09:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productcategory',
            name='group',
        ),
        migrations.AddField(
            model_name='productcategory',
            name='group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, related_name='categories', to='catalog.productcategorygroup', verbose_name='группа категории'),
            preserve_default=False,
        ),
    ]
