# Generated by Django 5.2.1 on 2025-06-10 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_remove_productcategory_group_productcategory_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdoc',
            name='name',
            field=models.CharField(max_length=100, verbose_name='название документа'),
        ),
    ]
