# Generated by Django 5.2.1 on 2025-06-14 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_productdoc_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='remainder',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='актуальный остаток'),
        ),
    ]
