# Generated by Django 5.2.1 on 2025-06-20 12:52

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


def bind_current_price(apps, schema_editor):
    Product = apps.get_model("catalog", "Product")
    ProductPrice = apps.get_model("catalog", "ProductPrice")
    for p in Product.objects.all():
        ProductPrice.objects.create(price=p.price, discount=p.discount, product=p)


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0004_alter_product_remainder"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductPrice",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("order", models.PositiveSmallIntegerField(default=32000, verbose_name="очередность")),
                ("name", models.CharField(blank=True, max_length=24, verbose_name="вариация товара")),
                ("price", models.PositiveIntegerField(verbose_name="цена")),
                (
                    "discount",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MaxValueValidator(99),
                            django.core.validators.MinValueValidator(1),
                        ],
                        verbose_name="скидка (%)",
                    ),
                ),
            ],
            options={
                "verbose_name": "цена",
                "verbose_name_plural": "цены",
                "ordering": ("order", "id"),
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="productprice",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="prices", to="catalog.product"
            ),
        ),
        migrations.AddConstraint(
            model_name="productprice",
            constraint=models.UniqueConstraint(fields=("product", "name"), name="unique_product_name"),
        ),
        migrations.AddConstraint(
            model_name="productprice",
            constraint=models.CheckConstraint(
                condition=models.Q(("discount__gte", 1), ("discount__lte", 99)),
                name="catalog_productprice_discount_range",
                violation_error_message="Скидка должна быть в диапазоне от 1 до 99",
            ),
        ),
        migrations.RunPython(bind_current_price, None),
        migrations.RemoveConstraint(
            model_name="product",
            name="catalog_product_discount_range",
        ),
        migrations.RemoveField(
            model_name="product",
            name="discount",
        ),
        migrations.RemoveField(
            model_name="product",
            name="price",
        ),
    ]
