# Generated by Django 5.2.1 on 2025-07-01 21:17

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_productprice_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategory',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='описание'),
        ),
        migrations.AddField(
            model_name='productcategorygroup',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='описание'),
        ),
    ]
