# Generated by Django 5.2.1 on 2025-07-04 05:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_productcategory_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategoryGroupRedirectFrom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_slug', models.CharField(max_length=60, unique=True, verbose_name='старый url')),
                ('to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.productcategorygroup')),
            ],
            options={
                'verbose_name': 'Старый слаг (url)',
                'verbose_name_plural': 'Старые слаги (url)',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProductCategoryRedirectFrom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_slug', models.CharField(max_length=60, unique=True, verbose_name='старый url')),
                ('to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.productcategory')),
            ],
            options={
                'verbose_name': 'Старый слаг (url)',
                'verbose_name_plural': 'Старые слаги (url)',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProductRedirectFrom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_slug', models.CharField(max_length=60, unique=True, verbose_name='старый url')),
                ('to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.product')),
            ],
            options={
                'verbose_name': 'Старый слаг (url)',
                'verbose_name_plural': 'Старые слаги (url)',
                'abstract': False,
            },
        ),
    ]
