# Generated by Django 5.2.1 on 2025-08-12 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_productcategorygroupredirectfrom_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='best_price',
            field=models.BooleanField(default=False, verbose_name='гарантия лучшей цены'),
        ),
    ]
