# Generated by Django 5.2.1 on 2025-08-14 09:34

from django.db import migrations, models


def move_category(apps, schema_editor):
    Product = apps.get_model("catalog", "Product")
    for p in Product.objects.all():
        p.categories.add(p.category)


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0008_product_best_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="categories",
            field=models.ManyToManyField(
                related_name="products", to="catalog.productcategory", verbose_name="категории товара"
            ),
        ),
        migrations.RunPython(move_category, None),
        migrations.RemoveField(
            model_name="product",
            name="category",
        ),
    ]
