# Generated by Django 5.2.1 on 2025-08-14 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_remove_product_category_product_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='hidden',
            field=models.BooleanField(default=False, verbose_name='скрыть из каталога'),
        ),
    ]
