# Generated by Django 5.2.1 on 2025-08-14 13:19

import shared.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_product_hidden'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategory',
            name='image',
            field=models.ImageField(null=True, upload_to=shared.utils.category_group_image_upload_to, verbose_name='картинка'),
        ),
    ]
