# Generated by Django 5.2.1 on 2025-08-14 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_productcategory_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='hidden',
            field=models.BooleanField(default=False, verbose_name='скрытый из каталога'),
        ),
    ]
