# Generated by Django 5.2.1 on 2025-08-15 13:55

import django.db.models.deletion
from django.db import migrations, models


def create_type(apps, schema_editor):
    ProductCategory = apps.get_model("catalog", "ProductCategory")
    ProductType = apps.get_model("catalog", "ProductType")
    for c in ProductCategory.objects.all():
        t = ProductType.objects.create(name=c.name)
        t.attributes.set(c.attributes.all())
        t.categories.add(c)
        products = c.products.all()
        for p in products:
            if p.categories.first() == c:
                t.products.add(p)


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0012_alter_product_hidden"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductType",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=48, unique=True, verbose_name="название")),
                (
                    "categories",
                    models.ManyToManyField(
                        related_name="types",
                        to="catalog.productcategory",
                        verbose_name="категории",
                        blank=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "тип товара",
                "verbose_name_plural": "типы товаров",
            },
        ),
        migrations.AlterModelOptions(
            name="attribute",
            options={"verbose_name": "характеристика товаров", "verbose_name_plural": "характеристики товаров"},
        ),
        migrations.AddField(
            model_name="attribute",
            name="type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attributes",
                to="catalog.producttype",
                verbose_name="тип товара",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="products",
                to="catalog.producttype",
                verbose_name="тип товара",
            ),
        ),
        migrations.AddConstraint(
            model_name="attribute",
            constraint=models.UniqueConstraint(fields=("name", "type"), name="unique_attribute_type"),
        ),
        migrations.RunPython(create_type, None),
        migrations.RemoveConstraint(
            model_name="attribute",
            name="unique_attribute_name_category",
        ),
        migrations.RemoveField(
            model_name="attribute",
            name="category",
        ),
    ]
