# Generated by Django 5.2.1 on 2025-08-16 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0013_producttype_alter_attribute_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="attribute",
            name="unit",
            field=models.CharField(blank=True, max_length=16, verbose_name="единица измерения"),
        ),
    ]
